### ISSUE TITLE
Group::search issue

### ISSUE THREAD

**Issue by centexdabull** [moxiworks-platform/moxiworks-php#1]
Contacts property of \MoxiworksPlatform\Group::search() result is always null.
Expected array of contact objects

Code:
$moxi_works_agent_id = 'partnertest@o365-qa.moxiworks.com';
$moxi_works_agent_uuid = '7819d2c8-d755-41d4-a2af-f786c058827e'; 
// Search for Groups or return all Groups for an Agent on Moxi Works Platform.
$groups = \MoxiworksPlatform\Group::search(['moxi_works_agent_id' => $moxi_works_agent_id, 'moxi_works_group_name' => '']);

var_dump($groups);

Output:
array (size=4)
  0 => 
    object(MoxiworksPlatform\Group)[26]
      public 'moxi_works_agent_id' => null
      public 'moxi_works_group_name' => string 'Christmas Cards' (length=15)
      public 'contacts' => null
  1 => 
    object(MoxiworksPlatform\Group)[28]
      public 'moxi_works_agent_id' => null
      public 'moxi_works_group_name' => string 'Direct Mail' (length=11)
      public 'contacts' => null
  2 => 
    object(MoxiworksPlatform\Group)[2]
      public 'moxi_works_agent_id' => null
      public 'moxi_works_group_name' => string 'Quantum Digital' (length=15)
      public 'contacts' => null
  3 => 
    object(MoxiworksPlatform\Group)[4]
      public 'moxi_works_agent_id' => null
      public 'moxi_works_group_name' => string 'Yellow category' (length=15)
      public 'contacts' => null

**Comment by tres** [comment]
Hi,

It looks like the library wasn't updated to reflect updated group search response attributes.

The response object was modified because group lookups are very expensive & slow, so we modified the response so we give an index of group names & group IDs & the ID can then be used in the find method to get the contacts. This was done almost immediately after Groups were initially released but we missed the analog updates to the libraries when the change was made.

Sorry for the built-in entropy here. I'll get the library updated and a new version pushed as soon as I can. 

Thanks for your report!

Tres

**Comment by tres** [comment]
https://moxiworks-platform.github.io/#group-index

we're now returning 

moxi_works_group_name
moxi_works_group_id
transient

in the search response

**Comment by tres** [comment]
Hi, 

I've pushed 0.11.3 & it looks like packagist has picked it up:

https://packagist.org/packages/moxiworks/moxiworks_platform

Thanks again for your report!
